# Generated by Django 2.0.2 on 2018-03-17 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(default='null', max_length=200)),
                ('user_id', models.IntegerField(default=0, null=True)),
                ('f_item', models.CharField(default='null', max_length=200)),
                ('f_options_list', models.CharField(default='null', max_length=500)),
                ('f_options', models.CharField(default='null', max_length=500)),
                ('f_last_q', models.CharField(default='null', max_length=200)),
                ('f_last_date', models.DateField(default=None, null=True)),
                ('how_often', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('q_item', models.CharField(default='null', max_length=200)),
                ('q_options_list', models.CharField(default='null', max_length=500)),
                ('q_last', models.CharField(default='null', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('relation', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Question'),
        ),
    ]
