# Generated by Django 2.0.2 on 2018-03-18 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(default='null', max_length=200)),
                ('user_id', models.IntegerField(default=0, null=True)),
                ('f_item', models.CharField(default='null', max_length=200)),
                ('f_options_list', models.CharField(default='null', max_length=500)),
                ('f_options', models.CharField(default='', max_length=500)),
                ('f_last_q', models.CharField(default='null', max_length=200)),
                ('f_last_date', models.DateField(default=None, null=True)),
                ('how_often', models.IntegerField(default=0, null=True)),
                ('notification_text', models.CharField(default='null', max_length=200)),
                ('img_url', models.CharField(default='null', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0, null=True)),
                ('favorite_id', models.IntegerField(default=0, null=True)),
                ('start_date', models.DateField(default=None, null=True)),
                ('notification_text', models.CharField(blank=True, default='', max_length=500)),
                ('done', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('q_item', models.CharField(default='null', max_length=200)),
                ('q_options_list', models.CharField(default='null', max_length=500)),
                ('q_options_selected', models.CharField(blank=True, default='', max_length=500)),
                ('q_last', models.CharField(default='null', max_length=200)),
                ('notification_text', models.CharField(default='null', max_length=200)),
                ('img_url', models.CharField(default='null', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('relation', models.IntegerField(default=0, null=True)),
            ],
        ),
    ]
