# Generated by Django 2.0.2 on 2018-03-17 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(default='null', max_length=255),
            preserve_default=False,
        ),
    ]
