# Generated by Django 2.0.2 on 2018-03-17 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='q_options_select',
            field=models.CharField(default='', max_length=500),
        ),
    ]
