# Generated by Django 2.0.2 on 2018-03-17 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_question_q_options_select'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='q_options_select',
        ),
        migrations.AddField(
            model_name='question',
            name='q_options_selected',
            field=models.CharField(default='', max_length=500),
        ),
    ]
