# Generated by Django 2.0.2 on 2018-03-17 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20180317_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='q_options_selected',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
