# Generated by Django 2.0.2 on 2018-03-17 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20180317_0821'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_id', models.IntegerField(default=0, null=True)),
                ('done', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.AlterField(
            model_name='favoriteitems',
            name='f_options',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
